name: Python

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set TimeZone'
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'Install Requirements'
        run: pip install -r src/requirements.txt

      - name: 'Run Script'
        run: python src/main.py >> log/run.log
        env:
          pg_appid: ${{ secrets.pg_appid }}
          pg_msdkEncodeParam: ${{ secrets.pg_msdkEncodeParam }}
          pg_openid: ${{ secrets.pg_openid }}
          pg_sig: ${{ secrets.pg_sig }}
          pg_timestamp: ${{ secrets.pg_timestamp }}
          pg_roleId: ${{ secrets.pg_roleId }}
          pg_userId: ${{ secrets.pg_userId }}
          pg_token: ${{ secrets.pg_token }}
          smoba_roleId: ${{ secrets.smoba_roleId }}
          smoba_userId: ${{ secrets.smoba_userId }}
          smoba_token: ${{ secrets.smoba_token }}

      - name: 'Auto Commit'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          file_pattern: log/run.log
          commit_message: update run.log
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
