name: Python

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set TimeZone'
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'Install Requirements'
        run: pip install -r src/requirements.txt

      - name: 'Run Script'
        run: python src/main.py
        env:
          pushplus_token: ${{ secrets.pushplus_token }}
          pg_enable: ${{ secrets.pg_enable }}
          pg_appid: ${{ secrets.pg_appid }}
          pg_msdkEncodeParam: ${{ secrets.pg_msdkEncodeParam }}
          pg_openid: ${{ secrets.pg_openid }}
          pg_sig: ${{ secrets.pg_sig }}
          pg_timestamp: ${{ secrets.pg_timestamp }}
          pg_roleId: ${{ secrets.pg_roleId }}
          pg_userId: ${{ secrets.pg_userId }}
          pg_token: ${{ secrets.pg_token }}
          smoba_enable: ${{ secrets.smoba_enable }}
          smoba_roleId: ${{ secrets.smoba_roleId }}
          smoba_userId: ${{ secrets.smoba_userId }}
          smoba_token: ${{ secrets.smoba_token }}
          smoba_sMSDKUrlParam: ${{ secrets.smoba_sMSDKUrlParam }}
          smoba_sOpenId: ${{ secrets.smoba_sOpenId }}
          smoba_sCampUserId: ${{ secrets.smoba_sCampUserId }}
